### ISSUE TITLE
server returned http response code: 400 for url

### ISSUE THREAD

**Issue by PapiChase** [DarkEyeDragon/ImageUtils#2]
https://user-images.githubusercontent.com/40330852/48121700-79840880-e22a-11e8-939a-d9458de5aa40.png
https://user-images.githubusercontent.com/40330852/48121736-96b8d700-e22a-11e8-8827-ca00002cbe41.png
i got this problem and i have these settings, not exactly sure what the problem is but i hope you can get something outta it

**Comment by DarkEyeDragon** [comment]
I've just tested on the latest version (1.0.4) and on 1.0.1 and it seemed to work just fine with the settings you provided. The Imgur API didn't appear to be down either.

400 means its a bad request. 

From the imgur api:
> Status Code: 400
> This error indicates that a required parameter is missing or a parameter has a value that is out of bounds or otherwise incorrect. This status code is also returned when image uploads fail due to images that are corrupt or do not meet the format requirements.

It might be that your images are too large? Are you taking screenshots on a 4k screen maybe?

**Comment by MisterFixx** [comment]
This most likely means that some request variable was not URL encoded.
