### ISSUE TITLE
Suggestion: add option to create webhooks in discord

### ISSUE THREAD

**Issue by PixelmonPRO** [DarkEyeDragon/ImageUtils#3]
Hello! It would be nice to add the ability to links in images directly to the discord channel using webhooks)
And command, to take a screenshot, for example: `/screenshot` or alias `/screen`

**Comment by DarkEyeDragon** [comment]
I will have to look into this. I haven't really worked with web hooks yet. But it might be an interesting feature!

**Comment by DarkEyeDragon** [comment]
Side note: You can already create something like this. You could send the image to a webserver and let the server handle the webhook.

**Comment by wyatt-herkamp** [comment]
@DarkEyeDragon https://github.com/MrPowerGamerBR/TemmieWebhook  A webhook library if you are lazy

**Comment by DarkEyeDragon** [comment]
Feature added. Implemented on https://github.com/DarkEyeDragon/ImageUtils/commit/c9ab95a34e622422900669d4987458dc0612141d

It will be released with the 1.0.5 update this weekend.

**Comment by MisterFixx** [comment]
Great work, GG!
